#!/usr/bin/env bash

RBW_KEY=$1

if [ -z "$RBW_KEY" ]; then
  echo "Usage: $0 <key>"
  exit 1
fi

JSON_VALUES="$(rbw get $RBW_KEY --raw)"
uri=$(echo "$JSON_VALUES" | jq -r '.data.uris[0].uri')
tunnel=$(echo "$JSON_VALUES" | jq -r '.fields[] | select(.name=="tunnel") | .value')

# if uri is postgres
if [[ $uri = postgres* ]]; then
  export PGPASSWORD="$(rbw get $RBW_KEY)"
  export DB_UI_${RBW_KEY}="$uri"
else
  echo "Unsupported database type"
  exit 1
fi

ssh -N "$tunnel" &

PID=$!
nvim +DBUI
kill $PID
