#!/usr/bin/env ruby
# frozen_string_literal: true

# mise description="Create Random Password"

# @#$%^&*-_!+=[]{}|\:',.?/`~"();<>
puts Array.new(ARGV[0].to_i || 20) {
  (('a'..'z').to_a + ('A'..'Z').to_a + ('0'..'9').to_a + %w[! @ # $ % ^ & *]).sample
}.join
