#!/bin/bash

TARGET_PATH="$HOME/Library/Application Support/Claude/claude_desktop_config.json"

mcp_server='{}'

add_to_mcp_server() {
  local key=$1
  local value=$2

  local expanded_value=$(echo "$value" | envsubst)

  mcp_server=$(echo $mcp_server |
    jq --arg key "$key" \
       --argjson value "$expanded_value" \
       '.["mcpServers"][$key] = $value')
}

# add_to_mcp_server memory '{
#   "command": "npx",
#   "args": ["-y", "@modelcontextprotocol/server-memory"]
# }'

# add_to_mcp_server sqlite '{
#   "command": "uvx",
#   "args": ["mcp-server-sqlite", "--db-path", "$HOME/test.sqlite"]
# }'

# add_to_mcp_server playwright '{
#   "command": "$HOME/.local/bin/mise",
#   "args": [
#     "x", "node@22",
#     "--",
#     "npx", "-y", "@executeautomation/playwright-mcp-server"],
#   "env": {}
# }'

add_to_mcp_server playwright '{
  "command": "$HOME/.local/bin/mise",
  "args": [
    "x", "node@22",
    "--",
    "npx", "-y", "@playwright/mcp@latest"],
  "env": {}
}'

add_to_mcp_server claude_code '{
  "command": "$HOME/.local/bin/mise",
  "args": [
    "x", "node@22",
    "--",
    "claude", "mcp", "serve"],
  "env": {}
}'

# add_to_mcp_server figma '{
#   "command": "$HOME/.local/bin/mise",
#   "args": [
#     "x", "node@22",
#     "--",
#     "npx", "-y", "figma-developer-mcp", "--stdio"],
#   "env": {
#     "FIGMA_API_KEY": "$FIGMA_API_KEY"
#   }
# }'

echo "Before:"
cat "$TARGET_PATH" | jq
echo "----"
echo "After:"
echo "$mcp_server" | jq | tee "$TARGET_PATH"
