#!/bin/bash

echo '12312321'

if [[ -z "`git config --local --get user.email`" ]]; then
  # echo 'Run one of the following first:'
  # echo
  # echo '  git config --local user.email ssiumha@gmail.com'
  # echo '  git config --local user.name ssiumha'
  # echo
  # exit 1
fi
