#!/usr/bin/env ruby
#MISE description="Check target domain inspect"

require_relative '../common'

domain = ARGV.pop

if domain.nil?
  puts "Usage: inspect-domain <domain>"
  exit 1
end

puts [
  "\n======== whois ========".green,
  `whois #{domain}`,

  "\n======== nslookup ========".green,
   `nslookup #{domain}`,

  "\n======== ping ========".green,
   `ping -c 1 #{domain}`,

  "\n======== dig ========".green,
   `dig #{domain}`
].join("\n")
