#!/bin/sh
total=$(($(sysctl -n hw.memsize)/1024/1024/1024))
vm_stat | awk -v total=$total '
  NR==1 {for(i=1;i<=NF;i++) if($i ~ /^[0-9]+$/) page=$i}
  /Pages active/     {gsub(/\./,"",$3); active=$3}
  /Pages speculative/{gsub(/\./,"",$3); spec=$3}
  /Pages wired/      {gsub(/\./,"",$4); wired=$4}
  END {
    used=(active+spec+wired)*page/1024/1024/1024
    printf "%.1f/%dGB\n", used, total
  }'
