#!/usr/bin/env ruby

# -1743 System Events 에러 발생시
#  설정 > 자동화 검색 > 응용 프로그램이 Mac을 자동화하는 것을 허용 메뉴에서
#    > WezTerm 의 system Events 활성화

def resize_window(app_name, x: 0, y: 0, width:, height:)
  src = <<-EOF
    tell application "System Events"
      set position of window 1 of process "#{app_name}" to {#{x}, #{y}}
      set size of window 1 of process "#{app_name}" to {#{width}, #{height}}
    end tell
  EOF
  system 'osascript', '-e', src
end

screen_width, screen_height = `system_profiler SPDisplaysDataType | grep Resolution | head -n 1`
  .match(/Resolution: (\d+) x (\d+)/)
  .captures
  .map(&:to_i)
  .map { _1 / 2 } # retina display

running_apps = `osascript -e 'tell application "System Events" to name of every process where background only is false'`
  .split(', ')

app_sizes = {
  'Google Chrome' => :offset_right,
  'Arc' => :offset_right,
  'firefox' => :offset_right,
  'Safari' => :offset_right,
  # /Emacs.+/ => :offset_right,
  'Slack' => :full,
  'ChatGPT' => :center,
}

# TODO: Arc, Emacs not working
running_apps.each do |app_name|
  app_size = app_sizes.find { |k, v| app_name.match?(k) }
  next if app_size.nil?

  x, y = 0, 0
  width, height = screen_width, screen_height

  puts app_size.join(' => ')

  case app_size.last
  when :offset_right then x += 250 and width -= 250
  when :center then x += 250 and width -= 500
  when :full
  end

  resize_window(app_name, x:, y:, width:, height:)
end
