#!/bin/bash

# %x09 : tab
# 20-99-99 branch_name author subject

git for-each-ref --sort=committerdate refs/heads/ --color=always \
  --format="%(HEAD) %(color:green)%(committerdate:short)%(color:reset) %09 %(color:yellow)%(refname:short)%(color:reset) %09 %(authorname) %09 %(contents:subject)" \
  | column -t -s $'\t' | fzf +s --tac --ansi | perl -pe 's/^\*//' | awk '{print $2}' | xargs -I% git checkout %

