#!/bin/bash
# git stash

git checkout $(git main-branch) &&
  git fetch $(git up-branch) $(git main-branch) &&
  git merge --ff-only $(git up-branch)/$(git main-branch) &&
  git checkout - &&
  git rebase $(git main-branch)

# git stash pop
