#!/usr/bin/env ruby

contexts = `kubectl config get-contexts -o name | fzf --multi --prompt="Select Kube Contexts > "`.lines.map(&:strip)
abort("No context selected") if contexts.empty?

id_map = {}
contexts.each do |ctx|
  ids = `kubectl --context=#{ctx} get nodes -o json | jq -r '.items[].spec.providerID'`
         .lines.map { |l| l.split('/').last.strip rescue nil }.compact
  ids.each { |id| id_map[id] = ctx.split(':').last }
end

instances = `aws ec2 describe-instances | jq -r '.Reservations[].Instances[] | [.InstanceId, (.Tags[]? | select(.Key=="Name") | .Value)? , .PrivateDnsName] | @tsv'`
             .lines.map { |l| l.strip.split("\t") }.sort_by { |id, name, _| name.to_s.downcase }
             .sort_by { |id, name| name.to_s.downcase }

puts "%-20s %-30s %-20s %-30s" % ["InstanceID", "Name", "K8s Context", "Node Name"]
puts "-" * 100
instances.each do |id, name, dns|
  puts "%-20s %-30s %-20s %-30s" % [id, name || 'N/A', id_map[id] || '-', dns || '-']
end
