views:
  # v1/pods@prefix-ns-*:
  # v1/pods@specific-namespace:
  #   columns:
  #     - NAMESAPCE|W => widemode only
  #     - NAMESAPCE|WR => widemode only, align right
  #     - NODE|H => do not display
  #     - ZORG:.spec.zips[?(@.type == 'zorg')].ip|WR  => json exp
  #     - X|T -> time column
  #     - X|N -> number column
  v1/pods:
    columns:
      - NAMESPACE
      - NAME
      - READY
      - RESTARTS
      - STATUS
      - AGE
      - CPU
      - MEM
      - '%CPU/R'
      - '%CPU/L'
      - '%MEM/R'
      - '%MEM/L'
      - IP
      - NODE
      # QOS PF LABELS
  v1/nodes:
    sortColumn: AGE:asc
    columns:
      # - NAME
      - INTERNAL-IP
      - STATUS
      # - ROLE
      - TAINTS
      - VERSION
      - PODS
      - AGE
      - '%CPU'
      - CPU
      - 'CPU/A'
      - '%MEM'
      - MEM
      - 'MEM/A'
      - TYPE:.metadata.labels.node\.kubernetes\.io/instance-type
      - ZONE:.metadata.labels.topology\.kubernetes\.io/zone
      - LABELS
